// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.grpc.api.proto;

public interface RPCDateRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.grpc.api.proto.RPCDateRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userName = 1;</code>
     *
     * @return The userName.
     */
    java.lang.String getUserName();

    /**
     * <code>string userName = 1;</code>
     *
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
    getUserNameBytes();
}
